#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# Add your custom logic above the visualizer emit block below.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Read Copilot CLI context from stdin (JSON payload)
_VIZ_STDIN=$(cat 2>/dev/null || echo '{}')
if [ -z "$_VIZ_STDIN" ]; then _VIZ_STDIN='{}'; fi
_vjq() { echo "$_VIZ_STDIN" | jq -r "$1" 2>/dev/null || true; }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
: "${TOOL_NAME:=$(_vjq '.tool_name // .toolName // empty')}"
: "${SESSION_ID:=$(_vjq '.session_id // .sessionId // empty')}"
: "${AGENT_NAME:=$(_vjq '.agent_name // .agentName // .active_agent // .activeAgent // .active_agent.name // .activeAgent.name // .active_agent.id // .activeAgent.id // .agent.name // .agent.id // .agent.slug // .actor.name // .name // empty')}"
: "${AGENT_TYPE:=$(_vjq '.agent_type // .agentType // .active_agent.type // .activeAgent.type // .toolArgs.agent_type // .tool_args.agent_type // empty')}"
: "${AGENT_TASK_NAME:=$(_vjq '.toolArgs.name // .tool_args.name // .task_name // .taskName // .task_description // .taskDescription // .task // .description // .name // empty')}"
: "${SUBAGENT_NAME:=$(_vjq '.subagent_name // .subagentName // .subagent.name // .subagent.id // .agent_name // .agentName // .agent.name // empty')}"
: "${AGENT_ID:=$(_vjq '.agent_id // .agentId // .agent.id // .actor.id // empty')}"
: "${SUBAGENT_ID:=$(_vjq '.subagent_id // .subagentId // .subagent.id // empty')}"
: "${AGENT_DISPLAY_NAME:=$(_vjq '.agent_display_name // .agentDisplayName // .agent.display_name // .agent.displayName // .actor.display_name // .display_name // .displayName // empty')}"
: "${SUBAGENT_DISPLAY_NAME:=$(_vjq '.subagent_display_name // .subagentDisplayName // .subagent.display_name // .subagent.displayName // .agent_display_name // .agentDisplayName // .display_name // .displayName // empty')}"
: "${AGENT_DESCRIPTION:=$(_vjq '.agent_description // .agentDescription // .agent.description // .actor.description // .description // empty')}"
: "${SUBAGENT_DESCRIPTION:=$(_vjq '.subagent_description // .subagentDescription // .subagent.description // .agent_description // .agentDescription // .description // empty')}"
: "${TASK_DESC:=$(_vjq '.task_description // .taskDescription // .task // .toolArgs.description // .tool_args.description // empty')}"
: "${AGENT_MESSAGE:=$(_vjq '.agent.message // .agent.finalMessage // .agent.output.summary // .message // empty')}"
: "${MESSAGE:=$(_vjq '.error.message // .message // .output.message // .final_message // .finalMessage // empty')}"
: "${SUMMARY:=$(_vjq '.summary // .output.summary // .final_summary // .finalSummary // empty')}"
: "${RESULT:=$(_vjq '.result // empty')}"
: "${REASON:=$(_vjq '.reason // .stopReason // .stop_reason // .resultType // .status // empty')}"
: "${STATUS:=$(_vjq '.toolResult.resultType // .status // .tool_status // empty')}"
: "${ERROR_SUMMARY:=$(_vjq '.error.message // .error_summary // .errorSummary // empty')}"
: "${TOOL_ARGS:=$(_vjq '.toolArgs // empty')}"
: "${SKILL_NAME:=$(_vjq '.skill_name // .skillName // .skill.name // .tool.skill.name // .toolResult.skill.name // empty')}"
: "${SKILL_ID:=$(_vjq '.skill_id // .skillId // .skill.id // .tool.skill.id // .toolResult.skill.id // empty')}"
: "${TOOL_CALL_ID:=$(_vjq '.tool_call_id // .toolCallId // .tool_use_id // .toolUseId // empty')}"
: "${SOURCE:=$(_vjq '.source // empty')}"
: "${PROMPT:=$(_vjq '.prompt // .user_prompt // empty')}"
: "${NOTIFICATION_TYPE:=$(_vjq '.notification_type // .notificationType // empty')}"
: "${TITLE:=$(_vjq '.title // empty')}"
: "${CODE:=$(_vjq '.code // .error_code // empty')}"

# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
if [ -x "${REPO_ROOT}/.visualizer/emit-event.sh" ]; then
  _VIZ_PAYLOAD=$(jq -nc --arg prompt "${PROMPT:-}" '{"prompt":$prompt}' 2>/dev/null || echo '{}')
  "${REPO_ROOT}/.visualizer/emit-event.sh" userPromptSubmitted "${_VIZ_PAYLOAD}" "${SESSION_ID:-run-$$}" >&2 || true
fi

exit 0
