# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# The Copilot CLI fires a single postToolUse hook for both success and failure.
# This stub routes to the correct visualizer event type based on toolResult.resultType.
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir ".." ".." "..")).Path

# Read Copilot CLI context from stdin (JSON payload)
try { $_vizStdin = [Console]::In.ReadToEnd() } catch { $_vizStdin = '{}' }
if (-not $_vizStdin) { $_vizStdin = '{}' }
try { $_vizJson = $_vizStdin | ConvertFrom-Json } catch { $_vizJson = $null }
function _vizField([string[]]$names) { if (-not $_vizJson) { return '' }; foreach ($n in $names) { $v = $_vizJson.PSObject.Properties[$n]; if ($v -and $v.Value) { return [string]$v.Value } }; return '' }
function _vizNested([string]$path) { if (-not $_vizJson) { return '' }; $parts = $path -split '\.'; $cur = $_vizJson; foreach ($p in $parts) { if (-not $cur) { return '' }; $v = $cur.PSObject.Properties[$p]; if (-not $v) { return '' }; $cur = $v.Value }; if ($cur -is [string]) { return $cur } elseif ($cur) { return [string]$cur } else { return '' } }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
if (-not $env:TOOL_NAME)              { $env:TOOL_NAME = _vizField 'tool_name','toolName' }
if (-not $env:SESSION_ID)             { $env:SESSION_ID = _vizField 'session_id','sessionId' }
if (-not $env:AGENT_NAME)             { $v = _vizNested 'activeAgent.name'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'activeAgent.id'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'active_agent.name'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'active_agent.id'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'agent.name'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'agent.id'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'agent.slug'; if ($v) { $env:AGENT_NAME = $v } else { $v = _vizNested 'actor.name'; if ($v) { $env:AGENT_NAME = $v } else { $env:AGENT_NAME = _vizField 'agent_name','agentName','name' } } } } } } } } }
if (-not $env:AGENT_TYPE)             { $v = _vizNested 'activeAgent.type'; if ($v) { $env:AGENT_TYPE = $v } else { $v = _vizNested 'active_agent.type'; if ($v) { $env:AGENT_TYPE = $v } else { $v = _vizNested 'toolArgs.agent_type'; if ($v) { $env:AGENT_TYPE = $v } else { $v = _vizNested 'tool_args.agent_type'; if ($v) { $env:AGENT_TYPE = $v } else { $env:AGENT_TYPE = _vizField 'agent_type','agentType' } } } } }
if (-not $env:AGENT_TASK_NAME)        { $v = _vizNested 'toolArgs.name'; if ($v) { $env:AGENT_TASK_NAME = $v } else { $v = _vizNested 'tool_args.name'; if ($v) { $env:AGENT_TASK_NAME = $v } else { $env:AGENT_TASK_NAME = _vizField 'task_name','taskName','task_description','taskDescription','task','description','name' } } }
if (-not $env:SUBAGENT_NAME)          { $v = _vizNested 'subagent.name'; if ($v) { $env:SUBAGENT_NAME = $v } else { $v = _vizNested 'subagent.id'; if ($v) { $env:SUBAGENT_NAME = $v } else { $env:SUBAGENT_NAME = _vizField 'subagent_name','subagentName','agent_name','agentName' } } }
if (-not $env:AGENT_ID)               { $v = _vizNested 'agent.id'; if ($v) { $env:AGENT_ID = $v } else { $v = _vizNested 'actor.id'; if ($v) { $env:AGENT_ID = $v } else { $env:AGENT_ID = _vizField 'agent_id','agentId' } } }
if (-not $env:SUBAGENT_ID)            { $v = _vizNested 'subagent.id'; if ($v) { $env:SUBAGENT_ID = $v } else { $env:SUBAGENT_ID = _vizField 'subagent_id','subagentId' } }
if (-not $env:AGENT_DISPLAY_NAME)     { $v = _vizNested 'agent.display_name'; if ($v) { $env:AGENT_DISPLAY_NAME = $v } else { $v = _vizNested 'agent.displayName'; if ($v) { $env:AGENT_DISPLAY_NAME = $v } else { $v = _vizNested 'actor.display_name'; if ($v) { $env:AGENT_DISPLAY_NAME = $v } else { $env:AGENT_DISPLAY_NAME = _vizField 'agent_display_name','agentDisplayName','display_name','displayName' } } } }
if (-not $env:SUBAGENT_DISPLAY_NAME)  { $v = _vizNested 'subagent.display_name'; if ($v) { $env:SUBAGENT_DISPLAY_NAME = $v } else { $v = _vizNested 'subagent.displayName'; if ($v) { $env:SUBAGENT_DISPLAY_NAME = $v } else { $env:SUBAGENT_DISPLAY_NAME = _vizField 'subagent_display_name','subagentDisplayName','agent_display_name','agentDisplayName','display_name','displayName' } } }
if (-not $env:AGENT_DESCRIPTION)      { $v = _vizNested 'agent.description'; if ($v) { $env:AGENT_DESCRIPTION = $v } else { $v = _vizNested 'actor.description'; if ($v) { $env:AGENT_DESCRIPTION = $v } else { $env:AGENT_DESCRIPTION = _vizField 'agent_description','agentDescription','description' } } }
if (-not $env:SUBAGENT_DESCRIPTION)   { $v = _vizNested 'subagent.description'; if ($v) { $env:SUBAGENT_DESCRIPTION = $v } else { $env:SUBAGENT_DESCRIPTION = _vizField 'subagent_description','subagentDescription','agent_description','agentDescription','description' } }
if (-not $env:TASK_DESC)              { $v = _vizNested 'toolArgs.description'; if ($v) { $env:TASK_DESC = $v } else { $v = _vizNested 'tool_args.description'; if ($v) { $env:TASK_DESC = $v } else { $env:TASK_DESC = _vizField 'task_description','taskDescription','task' } } }
if (-not $env:AGENT_MESSAGE)          { $v = _vizNested 'agent.message'; if ($v) { $env:AGENT_MESSAGE = $v } else { $v = _vizNested 'agent.finalMessage'; if ($v) { $env:AGENT_MESSAGE = $v } else { $v = _vizNested 'agent.output.summary'; if ($v) { $env:AGENT_MESSAGE = $v } else { $env:AGENT_MESSAGE = _vizField 'message' } } } }
if (-not $env:MESSAGE)                { $v = _vizNested 'error.message'; if ($v) { $env:MESSAGE = $v } else { $v = _vizNested 'output.message'; if ($v) { $env:MESSAGE = $v } else { $v = _vizNested 'final_message'; if ($v) { $env:MESSAGE = $v } else { $v = _vizNested 'finalMessage'; if ($v) { $env:MESSAGE = $v } else { $env:MESSAGE = _vizField 'message' } } } } }
if (-not $env:SUMMARY)                { $v = _vizNested 'output.summary'; if ($v) { $env:SUMMARY = $v } else { $v = _vizNested 'final_summary'; if ($v) { $env:SUMMARY = $v } else { $v = _vizNested 'finalSummary'; if ($v) { $env:SUMMARY = $v } else { $env:SUMMARY = _vizField 'summary' } } } }
if (-not $env:RESULT)                 { $env:RESULT = _vizField 'result' }
if (-not $env:REASON)                 { $v = _vizField 'reason','stopReason','stop_reason','resultType','status'; if ($v) { $env:REASON = $v } }
if (-not $env:STATUS)                 { $v = _vizNested 'toolResult.resultType'; if ($v) { $env:STATUS = $v } else { $env:STATUS = _vizField 'status','tool_status' } }
if (-not $env:ERROR_SUMMARY)          { $v = _vizNested 'error.message'; if ($v) { $env:ERROR_SUMMARY = $v } else { $env:ERROR_SUMMARY = _vizField 'error_summary','errorSummary' } }
if (-not $env:TOOL_ARGS)              { $env:TOOL_ARGS = _vizField 'toolArgs' }
if (-not $env:SKILL_NAME)             { $v = _vizNested 'skill.name'; if ($v) { $env:SKILL_NAME = $v } else { $v = _vizNested 'tool.skill.name'; if ($v) { $env:SKILL_NAME = $v } else { $v = _vizNested 'toolResult.skill.name'; if ($v) { $env:SKILL_NAME = $v } else { $env:SKILL_NAME = _vizField 'skill_name','skillName' } } } }
if (-not $env:SKILL_ID)               { $v = _vizNested 'skill.id'; if ($v) { $env:SKILL_ID = $v } else { $v = _vizNested 'tool.skill.id'; if ($v) { $env:SKILL_ID = $v } else { $v = _vizNested 'toolResult.skill.id'; if ($v) { $env:SKILL_ID = $v } else { $env:SKILL_ID = _vizField 'skill_id','skillId' } } } }
if (-not $env:TOOL_CALL_ID)           { $env:TOOL_CALL_ID = _vizField 'tool_call_id','toolCallId','tool_use_id','toolUseId' }
if (-not $env:SOURCE)                 { $env:SOURCE = _vizField 'source' }
if (-not $env:PROMPT)                 { $env:PROMPT = _vizField 'prompt','user_prompt' }
if (-not $env:NOTIFICATION_TYPE)      { $env:NOTIFICATION_TYPE = _vizField 'notification_type','notificationType' }
if (-not $env:TITLE)                  { $env:TITLE = _vizField 'title' }
if (-not $env:CODE)                   { $env:CODE = _vizField 'code','error_code' }

# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
$_vizEmitScript = Join-Path $RepoRoot ".visualizer/emit-event.ps1"
if (Test-Path $_vizEmitScript) {
  try {
    if ($env:STATUS -eq 'failure' -or $env:STATUS -eq 'denied') {
      $_vizPayload = (ConvertTo-Json @{ toolName = $(if ($env:TOOL_NAME) { $env:TOOL_NAME } else { 'unknown' }); status = 'failure'; errorSummary = $(if ($env:ERROR_SUMMARY) { $env:ERROR_SUMMARY } else { '' }); toolArgs = $(if ($env:TOOL_ARGS) { try { $env:TOOL_ARGS | ConvertFrom-Json } catch { $env:TOOL_ARGS } } else { $null }); agentName = $(if ($env:AGENT_NAME) { $env:AGENT_NAME } elseif ($env:SUBAGENT_NAME) { $env:SUBAGENT_NAME } elseif ($env:AGENT_DISPLAY_NAME) { $env:AGENT_DISPLAY_NAME } else { '' }); agentDisplayName = $(if ($env:AGENT_DISPLAY_NAME) { $env:AGENT_DISPLAY_NAME } elseif ($env:SUBAGENT_DISPLAY_NAME) { $env:SUBAGENT_DISPLAY_NAME } else { '' }); taskDescription = $(if ($env:TASK_DESC) { $env:TASK_DESC } else { '' }); message = $(if ($env:AGENT_MESSAGE) { $env:AGENT_MESSAGE } elseif ($env:MESSAGE) { $env:MESSAGE } else { '' }); skillName = $(if ($env:SKILL_NAME) { $env:SKILL_NAME } else { '' }); skillId = $(if ($env:SKILL_ID) { $env:SKILL_ID } else { '' }); toolCallId = $(if ($env:TOOL_CALL_ID) { $env:TOOL_CALL_ID } else { '' }) } -Compress)
      & $_vizEmitScript -EventType "postToolUseFailure" -Payload $_vizPayload -SessionId $(if ($env:SESSION_ID) { $env:SESSION_ID } else { "run-$PID" }) 2>&1 | Out-Null
    } else {
      $_vizPayload = (ConvertTo-Json @{ toolName = $(if ($env:TOOL_NAME) { $env:TOOL_NAME } else { 'unknown' }); status = 'success'; toolArgs = $(if ($env:TOOL_ARGS) { try { $env:TOOL_ARGS | ConvertFrom-Json } catch { $env:TOOL_ARGS } } else { $null }); agentName = $(if ($env:AGENT_NAME) { $env:AGENT_NAME } elseif ($env:SUBAGENT_NAME) { $env:SUBAGENT_NAME } elseif ($env:AGENT_DISPLAY_NAME) { $env:AGENT_DISPLAY_NAME } else { '' }); agentDisplayName = $(if ($env:AGENT_DISPLAY_NAME) { $env:AGENT_DISPLAY_NAME } elseif ($env:SUBAGENT_DISPLAY_NAME) { $env:SUBAGENT_DISPLAY_NAME } else { '' }); taskDescription = $(if ($env:TASK_DESC) { $env:TASK_DESC } else { '' }); message = $(if ($env:AGENT_MESSAGE) { $env:AGENT_MESSAGE } elseif ($env:MESSAGE) { $env:MESSAGE } else { '' }); skillName = $(if ($env:SKILL_NAME) { $env:SKILL_NAME } else { '' }); skillId = $(if ($env:SKILL_ID) { $env:SKILL_ID } else { '' }); toolCallId = $(if ($env:TOOL_CALL_ID) { $env:TOOL_CALL_ID } else { '' }) } -Compress)
      & $_vizEmitScript -EventType "postToolUse" -Payload $_vizPayload -SessionId $(if ($env:SESSION_ID) { $env:SESSION_ID } else { "run-$PID" }) 2>&1 | Out-Null
    }
  } catch { <# visualizer emit errors are intentionally silenced #> }
}

exit 0
