#!/usr/bin/env bash
set -euo pipefail
# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# The Copilot CLI fires a single postToolUse hook for both success and failure.
# This stub routes to the correct visualizer event type based on toolResult.resultType.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# Read Copilot CLI context from stdin (JSON payload)
_VIZ_STDIN=$(cat 2>/dev/null || echo '{}')
if [ -z "$_VIZ_STDIN" ]; then _VIZ_STDIN='{}'; fi
_vjq() { echo "$_VIZ_STDIN" | jq -r "$1" 2>/dev/null || true; }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
: "${TOOL_NAME:=$(_vjq '.tool_name // .toolName // empty')}"
: "${SESSION_ID:=$(_vjq '.session_id // .sessionId // empty')}"
: "${AGENT_NAME:=$(_vjq '.agent_name // .agentName // .name // empty')}"
: "${SUBAGENT_NAME:=$(_vjq '.subagent_name // .agent_name // .agentName // empty')}"
: "${AGENT_DISPLAY_NAME:=$(_vjq '.agent_display_name // .agentDisplayName // .display_name // .displayName // empty')}"
: "${SUBAGENT_DISPLAY_NAME:=$(_vjq '.agent_display_name // .agentDisplayName // .display_name // .displayName // empty')}"
: "${AGENT_DESCRIPTION:=$(_vjq '.agent_description // .agentDescription // .description // empty')}"
: "${SUBAGENT_DESCRIPTION:=$(_vjq '.agent_description // .agentDescription // .description // empty')}"
: "${TASK_DESC:=$(_vjq '.task_description // .taskDescription // .task // empty')}"
: "${AGENT_MESSAGE:=$(_vjq '.message // empty')}"
: "${MESSAGE:=$(_vjq '.error.message // .message // empty')}"
: "${SUMMARY:=$(_vjq '.summary // empty')}"
: "${RESULT:=$(_vjq '.result // empty')}"
: "${REASON:=$(_vjq '.reason // empty')}"
: "${STATUS:=$(_vjq '.toolResult.resultType // .status // .tool_status // empty')}"
: "${ERROR_SUMMARY:=$(_vjq '.error.message // .error_summary // .errorSummary // empty')}"
: "${TOOL_ARGS:=$(_vjq '.toolArgs // empty')}"
: "${SOURCE:=$(_vjq '.source // empty')}"
: "${PROMPT:=$(_vjq '.prompt // .user_prompt // empty')}"
: "${NOTIFICATION_TYPE:=$(_vjq '.notification_type // .notificationType // empty')}"
: "${TITLE:=$(_vjq '.title // empty')}"
: "${CODE:=$(_vjq '.code // .error_code // empty')}"

# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
if [ -x "${REPO_ROOT}/.visualizer/emit-event.sh" ]; then
  if [ "${STATUS}" = "failure" ] || [ "${STATUS}" = "denied" ]; then
    _VIZ_PAYLOAD=$(jq -nc --arg tool "${TOOL_NAME:-unknown}" --arg err "${ERROR_SUMMARY:-}" '{"toolName":$tool,"status":"failure","errorSummary":$err}' 2>/dev/null || echo '{}')
    "${REPO_ROOT}/.visualizer/emit-event.sh" postToolUseFailure "${_VIZ_PAYLOAD}" "${SESSION_ID:-run-$$}" >&2 || true
  else
    _VIZ_PAYLOAD=$(jq -nc --arg tool "${TOOL_NAME:-unknown}" '{"toolName":$tool,"status":"success"}' 2>/dev/null || echo '{}')
    "${REPO_ROOT}/.visualizer/emit-event.sh" postToolUse "${_VIZ_PAYLOAD}" "${SESSION_ID:-run-$$}" >&2 || true
  fi
fi

exit 0
