# Stub hook generated by bootstrap-existing-repo.
# Copilot CLI passes hook context as JSON on stdin.
# Add your custom logic above the visualizer emit block below.
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir ".." ".." "..")).Path

# Read Copilot CLI context from stdin (JSON payload)
try { $_vizStdin = [Console]::In.ReadToEnd() } catch { $_vizStdin = '{}' }
if (-not $_vizStdin) { $_vizStdin = '{}' }
try { $_vizJson = $_vizStdin | ConvertFrom-Json } catch { $_vizJson = $null }
function _vizField([string[]]$names) { if (-not $_vizJson) { return '' }; foreach ($n in $names) { $v = $_vizJson.PSObject.Properties[$n]; if ($v -and $v.Value) { return [string]$v.Value } }; return '' }
function _vizNested([string]$path) { if (-not $_vizJson) { return '' }; $parts = $path -split '\.'; $cur = $_vizJson; foreach ($p in $parts) { if (-not $cur) { return '' }; $v = $cur.PSObject.Properties[$p]; if (-not $v) { return '' }; $cur = $v.Value }; if ($cur -is [string]) { return $cur } elseif ($cur) { return [string]$cur } else { return '' } }
# Extract fields from stdin JSON into env vars (stdin fills unset vars)
if (-not $env:TOOL_NAME)              { $env:TOOL_NAME = _vizField 'tool_name','toolName' }
if (-not $env:SESSION_ID)             { $env:SESSION_ID = _vizField 'session_id','sessionId' }
if (-not $env:AGENT_NAME)             { $env:AGENT_NAME = _vizField 'agent_name','agentName','name' }
if (-not $env:SUBAGENT_NAME)          { $env:SUBAGENT_NAME = _vizField 'subagent_name','agent_name','agentName' }
if (-not $env:AGENT_DISPLAY_NAME)     { $env:AGENT_DISPLAY_NAME = _vizField 'agent_display_name','agentDisplayName','display_name','displayName' }
if (-not $env:SUBAGENT_DISPLAY_NAME)  { $env:SUBAGENT_DISPLAY_NAME = _vizField 'agent_display_name','agentDisplayName','display_name','displayName' }
if (-not $env:AGENT_DESCRIPTION)      { $env:AGENT_DESCRIPTION = _vizField 'agent_description','agentDescription','description' }
if (-not $env:SUBAGENT_DESCRIPTION)   { $env:SUBAGENT_DESCRIPTION = _vizField 'agent_description','agentDescription','description' }
if (-not $env:TASK_DESC)              { $env:TASK_DESC = _vizField 'task_description','taskDescription','task' }
if (-not $env:AGENT_MESSAGE)          { $env:AGENT_MESSAGE = _vizField 'message' }
if (-not $env:MESSAGE)                { $v = _vizNested 'error.message'; if ($v) { $env:MESSAGE = $v } else { $env:MESSAGE = _vizField 'message' } }
if (-not $env:SUMMARY)                { $env:SUMMARY = _vizField 'summary' }
if (-not $env:RESULT)                 { $env:RESULT = _vizField 'result' }
if (-not $env:REASON)                 { $env:REASON = _vizField 'reason' }
if (-not $env:STATUS)                 { $v = _vizNested 'toolResult.resultType'; if ($v) { $env:STATUS = $v } else { $env:STATUS = _vizField 'status','tool_status' } }
if (-not $env:ERROR_SUMMARY)          { $v = _vizNested 'error.message'; if ($v) { $env:ERROR_SUMMARY = $v } else { $env:ERROR_SUMMARY = _vizField 'error_summary','errorSummary' } }
if (-not $env:TOOL_ARGS)              { $env:TOOL_ARGS = _vizField 'toolArgs' }
if (-not $env:SOURCE)                 { $env:SOURCE = _vizField 'source' }
if (-not $env:PROMPT)                 { $env:PROMPT = _vizField 'prompt','user_prompt' }
if (-not $env:NOTIFICATION_TYPE)      { $env:NOTIFICATION_TYPE = _vizField 'notification_type','notificationType' }
if (-not $env:TITLE)                  { $env:TITLE = _vizField 'title' }
if (-not $env:CODE)                   { $env:CODE = _vizField 'code','error_code' }

# --- Visualizer emit (auto-wired by bootstrap-existing-repo) ---
$_vizEmitScript = Join-Path $RepoRoot ".visualizer/emit-event.ps1"
if (Test-Path $_vizEmitScript) {
  try {
    $_vizPayload = (ConvertTo-Json @{ agentName = $(if ($env:AGENT_NAME) { $env:AGENT_NAME } elseif ($env:SUBAGENT_NAME) { $env:SUBAGENT_NAME } else { 'unknown' }); taskDescription = $(if ($env:TASK_DESC) { $env:TASK_DESC } else { '' }); message = $(if ($env:AGENT_MESSAGE) { $env:AGENT_MESSAGE } elseif ($env:MESSAGE) { $env:MESSAGE } else { '' }) } -Compress)
    & $_vizEmitScript -EventType "subagentStop" -Payload $_vizPayload -SessionId $(if ($env:SESSION_ID) { $env:SESSION_ID } else { "run-$PID" }) 2>&1 | Out-Null
  } catch { <# visualizer emit errors are intentionally silenced #> }
}

exit 0
