# PowerShell emit-event script generated by bootstrap-existing-repo.
param(
  [Parameter(Mandatory)][string]$EventType,
  [Parameter(Mandatory)][string]$Payload,
  [Parameter(Mandatory)][string]$SessionId
)
$ErrorActionPreference = "Stop"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot = (Resolve-Path (Join-Path $ScriptDir "..")).Path
$VisualizerRoot = "/home/mcfuzzysquirrel/Projects/agent-forge-visualizer"
$JsonlPath = Join-Path $RepoRoot ".visualizer" "logs" "events.jsonl"
$HttpEndpoint = "http://127.0.0.1:7070/events"
if ($env:VISUALIZER_HTTP_ENDPOINT) { $HttpEndpoint = $env:VISUALIZER_HTTP_ENDPOINT }
$StorePrompts = "false"
if ($env:VISUALIZER_STORE_PROMPTS) { $StorePrompts = $env:VISUALIZER_STORE_PROMPTS }

npx tsx "$VisualizerRoot/scripts/emit-event-cli.ts" `
  --eventType $EventType `
  --payload $Payload `
  --sessionId $SessionId `
  --repoPath $RepoRoot `
  --jsonlPath $JsonlPath `
  --httpEndpoint $HttpEndpoint `
  --storePrompts $StorePrompts
